// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://jfynsdvmmrdxzha25i33ywihpi.appsync-api.us-east-2.amazonaws.com/graphql",
      region: "us-east-2",
      defaultAuthMode: "apiKey",
      apiKey: "da2-fxsa54oh6vcy7fjhovic5akjim",
    },
  },
};

export default config;
